M48
; DRILL file KiCad 10.0.6 date 2026-09-29T12:08:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-29T12:08:36+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.048
%
G90
G05
T1
X18.723Y-40.7
X18.723Y-46.48
T2
X50.24Y-17.27
X54.94Y-17.27
M30
